services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - c:\_dev\dezoomify-processor\output\:/images:ro
      - thumbnails:/thumbnails
    environment:
      - TV_IP=${TV_IP:-192.168.0.105}
    restart: unless-stopped

volumes:
  thumbnails:
